# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload',
            field=models.FileField(default='', upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
