# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-03 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usa_website', '0002_blog_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.FileField(upload_to='usa_website/templates/usa_website/uploads/'),
        ),
    ]
